---
title: "Practice Quiz 1"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```
<style>body{text-align: justify}</style>
### 1.

```{r q1}
question("Which of the following classifications of variable types is false?",
         answer("Population of each state in the US $\\to$ continuous numerical",correct = TRUE),
         answer("Whether a student has previously taken a statistics course $\\to$ categorical"),
         answer("Customer satisfaction: very unsatisfied, unsatisfied, satisfied, very satisfied
         $\\to$ ordinal categorical"),
         answer("Student height $\\to$ continuous numerical"))
```

### 2.

```{r q2}
question("True or False: If subjects are randomly assigned to treatments, conclusions can be
         generalized to the population.",
         answer("TRUE"),
         answer("FALSE",correct = TRUE))
```

### 3.

```{r q3}
question("As part of a statistics project, Andrea would like to collect data on household size in
         her city. To do so, she asks each person in her statistics class for the size of their
         household, and reports that her sample is a simple random sample. However, this is not a
         simple random sample. Which of the following is the best reasoning for why this is not a
         random sample that is appropriate for this research question?",
         answer("Andrea did not block for any variables that might influence the response."),
         answer("Andrea did not use a stratified sample."),
         answer("Andrea did not use any randomization; she took a convenience sample.",
                correct = TRUE))
```

### 4.

```{r q4}
question("Which of the following is not one of the four principles of experimental design?",
         answer("replicate"),
         answer("randomize"),
         answer("stratify",correct = TRUE))
```

### 5.

```{r q5}
question("True or False: Stratified sampling allows for controlling for possible confounders in
         the sampling stage, while blocking allows for controlling for such variables during
         random assignment.",
         answer("TRUE",correct = TRUE),
         answer("FALSE"))
```