---
title: "Practice Quiz 1"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup,include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE,comment = '')
```
<style>body{text-align: justify}</style>

### 1.

```{r q1}
question("Julia is having an outdoor wedding ceremony tomorrow.  In recent years, it has rained on average
         50 days per year.  Unfortunately, the meteorologist has predicted rain for her wedding day.  When
         it rains, the meteorologist will have correctly predicted it 80 percent of the time. When it does
         not rain, the meteorologist will have incorrectly predicted rain 30 percent of the time.  Given
         this information, what is the probability that it rains on Julia's wedding day?",
         answer("13.7%"),answer("29.7%",correct = TRUE),answer("72.7%"),answer("88.8%"))
```

```{r q1a,exercise = TRUE}
# P(predict rain | rain) = 0.80
# P(predict rain | no rain) = 0.30
# P(rain) = 50/365
# Compute P(rain | predict rain)

```

```{r q1a-solution}
p <- 50/365
p_predict.rain_rain    <- 0.8
p_predict.rain_no.rain <- 0.3
p_rain_predict.rain <- p_predict.rain_rain * p / (p_predict.rain_rain * p + p_predict.rain_no.rain * (1 - p))
round(p_rain_predict.rain,3) * 100
```

### 2.

```{r q2}
question("Which of the following do not impact decisions based on frequentist inference?",
         answer("Significance level"),
         answer("Type 1 error rate"),
         answer("Posterior probability",correct = TRUE),
         answer("The null hypothesis"))
```

### 3.

```{r q3}
question("Suppose 20 people are randomly sampled from the population and their gender is recorded. Which of the 
         following best represents the likelihood of the number of males observed k?",
         answer("The probability of at least k males in 20 people, given p 
                (the true population proportion of males)."),
         answer("The probability of observing exactly k males in 20 people, given p (the true population proportion of 
         males).",correct = TRUE),
         answer("The probability of observing exactly k males in 20 people, given p (the true population proportion of 
         males) and the posterior distribution of p."),
         answer("The probability of observing exactly k males in 20 people, given p (the true population proportion of 
         males) and the prior beliefs about p ."))
```

### 4.

```{r q4}
question("Which of the following statements is consistent with both Bayesian and frequentist
         interpretations of probability?",
         answer("Probability is a measure of the likelihood that an event will occur.",correct = TRUE),
         answer("Probability can be represented by a degree of belief, which changes as more data are collected."),
         answer("Probability can be represented by the long-run frequency of an event divided by 
                the number of trials."),
         answer("Probability is the tendency of an experiment to produce a certain outcome, even if it
         is performed only once."))
```

### 5.

```{r q5}
question("You are told that a coin has one of the following, with the probability of heads under that event noted next 
         to it in parentheses:</br>
         * a strong tails bias (p = 0.2)</br>
         * a weak tails bias (p = 0.4)</br>
         * no bias (p = 0.5)</br>
         * a weak heads bias (p = 0.6)</br>
         * a strong heads bias (p = 0.8)</br>
         You assign a prior probability of 1/2 that the coin is fair and distribute the remaining 1/2 prior probability
         equally over the other four possible scenarios. You flip the coin three times and it comes up heads all three 
         times. What is the posterior probability that the coin is biased towards heads?",
         answer("0.25"),answer("0.39"),answer("0.56",correct = TRUE),answer("0.73"))
```

```{r q5a,exercise = TRUE}
## Make Calculations Here

```

```{r q5a-solution}
p <- c(.2,.4,.5,.6,.8)
prior <- c(0.125,0.125,0.5,0.125,0.125)
likelihood <- dbinom(3,3,p)
nominator <- likelihood * prior
nominator /sum(nominator) -> posterior
sum(posterior[4:5])
```