---
title: "Practice Quiz 2"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```
<style>body{text-align: justify}</style>
### 1.

```{r q1}
question("Which of the below data sets has the lowest standard deviation? You do not need to 
         calculate the exact standard deviations to answer this question.",
         answer("0,1,3,3,3,5,6"),
         answer("0,1,2,3,4,5,6"),
         answer("0, 25, 50, 100, 125, 150, 1000"),
         answer("100, 100, 100, 100, 100, 100, 101",correct = TRUE))
```

### 2.

```{r q2}
question("True or False: The statistic mean/median (mean divided by median) can be used as a 
         measure of skewness (either right or left). Suppose we are dealing with a distribution
         where the minimum is 0.5. If this statistic (mean/median) is less than 1, the
         distribution is most likely left skewed.",
         answer("TRUE",correct = TRUE),
         answer("FALSE"))
```

### 3.

```{r q3}
question("True or False: You are going to collect income data from a right-skewed distribution of 
         incomes of politicians. If you take a large enough sample from that distribution, the 
         sample mean and the sample median will always have the same value.",
         answer("TRUE"),
         answer("FALSE",correct = TRUE))
```

### 4.

```{r q4}
question("True or False: A mosaic plot is useful for visualizing the relationship between a
         numerical and a categorical variable.",
         answer("TRUE"),
         answer("FALSE",correct = TRUE)
)
```

### 5.

```{r q5}
question("Does meditation cure insomnia? Researchers randomly divided 400 people into two equal-  
         sized groups. One group meditated daily for 30 minutes, the other group attended a 2-hour
         information session on insomnia. At the beginning of the study, the average difference
         between the number of minutes slept between the two groups was about 0. After the study,
         the average difference was about 32 minutes, and the meditation group had a higher
         average number of minutes slept. To test whether an average difference of 32 minutes
         could be attributed to chance, a statistics student decided to conduct a randomization
         test. She wrote the number of minutes slept by each subject in the study on an index
         card. She shuffled the cards together very well, and then dealt them into two equal-sized
         groups.Which of the following best describes the outcome?",
         answer("The average difference between the two stacks of cards will
                be about 0 minutes.",correct = TRUE),
         answer("If meditation is effective, the average difference between the two stacks of 
         cards will be more than 32 minutes."),
         answer("The average difference between the two stacks of cards will be about 32 minutes."
         ))
```