---
title: "Quiz 2"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup,include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE,comment = '')
```
<style>body{text-align: justify}</style>


### 1.

```{r q1}
question("Which of the following statements is true of a probability mass function but not a probability density function?", 
    answer("The probability that a random variable X is equal to a specific value x can be greater than zero.",correct = TRUE),
    answer("The function sums to (or integrates to) one over its domain."),
    answer("The probability that a random variable X is between a and b is the area under the function between a and b."),
    answer("The function takes on only non-negative values."))
```

### 2.

<b>Below are plots of the prior distribution for a parameter θ and the likelihood as a function of θ based on
10 observed data points.</b>

```{r fig-question}
grid::grid.raster(png::readPNG("fig1.png"))
```

```{r fig1,fig.cap = '(a)'}
grid::grid.raster(png::readPNG("figA.png"))
```

```{r fig2,fig.cap = '(b)'}
grid::grid.raster(png::readPNG("figB.png"))
```

```{r fig3,fig.cap = '(c)'}
grid::grid.raster(png::readPNG("figC.png"))
```

```{r fig4,fig.cap = '(d)'}
grid::grid.raster(png::readPNG("figD.png"))
```

```{r q2}
question('Which of the following is most likely to be the posterior distribution of $\\theta$?',
         answer("a"),answer("b"),answer("c",correct = TRUE),answer("d"))
```


### 3.

```{r q3}
question("Which of the following distributions would be the best choice of prior to use if you
         wanted to determine if a coin is fair when you have a strong belief that the coin is biased towards heads?
         (Assume a model where we call heads a success and tails a failure).",
         answer("Beta(50, 50)"),
         answer("Beta(9,1)"),
         answer("Beta(90,10)",correct = TRUE),
         answer("Beta (10, 90)"),
         answer("Beta(1,9)"))
```

### 4. 

```{r q4}
question("You are trying to model the number of fireworks that go off per minute during a fireworks show. 
         You decide to model this with a Poisson distribution with rate $\\lambda$, imposing a Gamma prior on
         $\\lambda$ for conjugacy.  You want the prior to have mean equal to 3 and standard deviation equal to 1.
         Which of the following priors represents your beliefs?",
         answer(sprintf("$\\Gamma\\left(k = 3,\\theta = 1\\right)$")),
         answer(sprintf("$\\Gamma\\left(k = 1,\\theta = 3\\right)$")),
         answer(sprintf("$\\Gamma\\left(k = 9,\\theta = \\frac{1}{3}\\right)$"),correct = TRUE),
         answer(sprintf("$\\Gamma\\left(k = \\frac{1}{3},\\theta = 9\\right)$")))
```


### 5.

```{r q5}
question("If John is trying to perform a Bayesian analysis to make inferences about the
         proportion of defective electric toothbrushes, which of the following
         distributions represents the a conjugate 
         prior for the proportion p?", 
         answer("Poisson"),answer("Beta",correct = TRUE),answer("Normal"),
         answer("Gamma"))
```

### 6.

```{r q6}
question("You are hired as a data analyst by politician A. She wants to know the proportion
         of people in Metrocity who favor her over politician B. From previous poll
         numbers, you place a Beta(40,60) prior on the proportion. From polling 200
         randomly sampled people in Metrocity, you find that 103 people prefer politician
         A to politician B. What is the posterior distribution of the proportion of
        voters who favor politician A?",
        answer("Beta(103, 97)"),
        answer("Beta(163, 137)"),
        answer("Beta(142, 156)"),answer("Beta(143, 157)",correct = TRUE))
```

### 7.

```{r q7}
question("You are hired as a data analyst by politician A. She wants to know the proportion
         of people in Metrocity who favor her over politician B. From previous poll
         numbers, you place a Beta(40,60) prior on the proportion. From polling 200
         randomly sampled people in Metrocity, you find that 103 people prefer politician
         A to politician B. What is the posterior probability that the majority of
         people prefer politician A to politican B (i.e. P(p>0.5|data))?",
         answer("0.198"),answer("0.209",correct = TRUE),answer("0.664"),answer("0.934"))
```

```{r q7a,exercise = TRUE}

```

```{r q7a-solution}
pbeta(.5,143,157,lower.tail = F)
```

### 8. 

```{r q8}
question("An engineer has just finished building a new production line for 
         manufacturing widgets. They have no idea how likely this process is to 
         produce defective widgets so they plan to run two separate runs of 15 
         widgets each. The first run produces 3 defective widgets and the second 5
         defective widgets. We represent our lack of apriori knowledge of the probability 
         of producing a defective widgets, p, using a flat, uninformative prior Beta(1,1).
         What should the posterior distribution of p be after the first run is finished? And
         after the second?",
        answer("After the first run, Beta(3,12). After the second run, Beta(5,10)."),
        answer("After the first run, Beta(4,13). After the second run, Beta(9,23).",correct = TRUE),
        answer("After the first run, Beta(3,12). After the second run, Beta(8,22)."),
        answer("After the first run, Beta(4,13). After the second run, Beta(6,11)."))
```

### 9.

```{r q9}
question("Suppose we are interested in modeling the number of airline passenger deaths per year, 
          assuming that the number of deaths follows a Poisson distribution.  If we observe data for one year, 
          record a total of 761 deaths, and find that our posterior distribution of the annual rate of passenger deaths 
          $\\lambda$ is $\\Gamma\\left(862,\\frac{12}{13}\\right)$, what was our conjugate prior distribution?",
         answer("Gamma(101,12)",correct = TRUE),answer("Gamma(862, 1)"),answer("Gamma(100, 13)"),answer("Gamma(761, 1)"))
```

```{r q9a,exercise = TRUE}

```

### 10.

```{r q10}
question("Suppose that the number of fish that Hans catches in an hour follows a Poisson
          distribution with rate $\\lambda$.  If the prior on $\\lambda$ is Gamma(1,1) and Hans
         catches no fish in five hours, what is the posterior distribution for $\\lambda$?",
         answer(sprintf("$\\Gamma(k=1,\\theta = \\frac{1}{6})$"),correct = TRUE),
         answer(sprintf("$\\Gamma(k=2,\\theta = \\frac{1}{6})$")),
         answer(sprintf("$\\Gamma(k=1,\\theta = \\frac{1}{5})$")),
         answer(sprintf("$\\Gamma(k=2,\\theta = \\frac{1}{5})$")))
```

```{r 10a,exercise = TRUE}

```

### 11.

```{r q11}
question("The posterior distribution for a mean of a normal likelihood, with a known variance $\\sigma^2$ and data
         $x_1,x_2,…,x_n$ and a normal prior with mean $\\mu$ and variance  has the following distribution: 
         $\\mu\\sim\\mathcal{N}\\left(\\left(\\frac{\\mu_0}{\\sigma_0^2} +\\frac{\\sum\\limits_{i=1}^{n}x_i}{\\sigma^2}\\right)\\Large{/}\\left(\\frac{1}{\\sigma_0^2}+\\frac{n}{\\sigma^2}\\right),\\left(\\frac{1}{\\sigma_0^2}+\\frac{n}{\\sigma^2}\\right)^{-1}\\right)$
         If you were to collect a large amount of data, how can you simplify the formulas given above? Hint - both n 
         and $\\sum\\limits_{i}^{n}x_{i}$ are very large relative to $\\mu_{0}$ and $\\sigma_{0}^{2}$.",
         answer("$\\mu\\sim\\mathcal{N}\\left(\\mu_{0},\\sigma_{0}^{2}\\right)$"),
         answer("$\\mu\\sim\\mathcal{N}\\left(\\frac{\\sum\\limits_{i=1}^{n}x_{i}}{n},\\sigma^2\\right)$"),
         answer("$\\mu\\sim\\mathcal{N}\\left(\\mu_{0},\\frac{\\sigma_{0}^{2}}{n}\\right)$"),
         answer("$\\mu\\sim\\mathcal{N}\\left(\\frac{\\sum\\limits_{i=1}^{n}x_{i}}{n},\\frac{\\sigma^2}{n}\\right)$",
                correct = TRUE))
```

### 12.

```{r q12}
question("A scientist is interested in estimating the average weight of male golden hamsters. They decide to use a Bayesian
         approach  to estimate $\\mu$ by creating a credible interval using a weakly informative prior. 
         The posterior distribution
         gives a 95% credible interval spanning 3.3 - 4.0 oz. According to this model, what is the probability that $\\mu$
         does not fall within this range?",
         answer("2.5%"),
         answer("5%",correct = TRUE),
         answer("95%"),
         answer("Either 0 or 1 since $\\mu$ is fixed, and must either be inside or outside the interval"))
```

### 13.

```{r q13}
question("True or False: When constructing a 95% credible interval, a good rule of thumb is to use 
         the shortest of all such intervals.",
         answer("True",correct = TRUE),answer("False"))
```

### 14.

```{r q14}
question("Suppose you are given a die and told that the die is either fair or is loaded (it 
         always comes up as a 6). Since most dice are not loaded, you place a prior probability of 0.8  on the outcome that 
         the die is fair. You roll a die and it comes up as a 6. What is the posterior probability that your
         next roll will also be a 6?",
         answer("11/15"),answer("2/3",correct = TRUE),answer("3/5"),answer("4/5"))
```

```{r q14a,exercise = TRUE}

```

```{r q14a-solution}
p <- 0.8*1/6 / (0.8*1/6 + 0.2 )
p * 1/6 + (1-p) *1
```

### 15.

<b>Below are plots of the prior distribution for a parameter θ and the likelihood as a function of θ based on
10 observed data points.</b>

```{r fig2-question}
grid::grid.raster(png::readPNG("fig2.png"))
```

```{r fig2A,fig.cap = '(a)'}
grid::grid.raster(png::readPNG("fig2A.png"))
```

```{r fig2B,fig.cap = '(b)'}
grid::grid.raster(png::readPNG("fig2B.png"))
```

```{r fig2C,fig.cap = '(c)'}
grid::grid.raster(png::readPNG("fig2C.png"))
```

```{r fig2D,fig.cap = '(d)'}
grid::grid.raster(png::readPNG("fig2D.png"))
```

```{r q15}
question('Which of the following is most likely to be the posterior distribution of $\theta$?',
         answer("a",correct = TRUE),answer("b"),answer("c"),answer("d"))
```


### 16.

```{r q16}
question("Suppose that a miner finds a gold nugget and wants to know the weight of the nugget in
          order to assess its value. The miner believes the nugget to be roughly 200
          grams, although she is uncertain about this quantity, so she puts a standard
          deviation of 50 grams on her estimate. She weighs the nugget on a scale which
          is known to weigh items with standard deviation 2 grams. The scale measures the
          nugget at 149.3 grams. What distribution summarizes the posterior beliefs of
          the miner?",
         answer(sprintf("$Normal(149.3,2^2)$")),
         answer(sprintf("$Normal(149.38,1.998^2)$"),correct = TRUE),
         answer(sprintf("$Normal(151.25,1.387^2)$")),
         answer(sprintf("$Normal(149.56,1.998^2)$")))
```

```{r q16a,exercise = TRUE}

```


```{r q16a-solution}
## look at the formulas at question 11
nominator <- (200/50^2 + 149.3/2^2)
denominator <- (1/50^2 + 1/2^2)
nominator/denominator -> mu
denominator^(-1) -> sigma
sprintf("The mu is %.3f and sigma is %.3f^2.",mu,sqrt(sigma))
```

### 17.

```{r q17}
question("Suppose you are given a coin and told that the die is either biased towards heads (p = 0.75 ) or 
          biased towards tails (p = 0.25 ). Since you have no prior knowledge about the bias of the coin,
          you place a prior probability of 0.5  on the outcome that the coin is biased towards heads.
          You flip the coin twice and it comes up tails both times. What is the posterior probability that your
          next flip will be heads?",
          answer("3/8"),answer("3/10",correct = TRUE),answer("1/3"),answer("2/3"))
```

```{r q17a,exercise = TRUE}

```


```{r q17a-solution}
p <- 0.25^2/(0.25^2 + 0.75^2)
p * 0.75 + (1-p) * 0.25
```

### 18.

```{r q18}
question("An obesity researcher is trying to estimate the probability that a random male between the ages of 35 and 44 
          weighs more than 270 pounds. In this analysis, weight is:",
          answer("A continuous random variable, since weight can theoretically take on any non-negative value in an interval.",
                 correct = TRUE),
          answer("A discrete random variable, since the 
                 number of men who weigh more than 270 pounds can take on only integer values."),
                 answer("A continuous random variable, since the prior probability that a random male 
                 between the ages of 35 and 44 weighs more than 270 pounds gives non-zero 
                 probability to all values between 0 and 1."),
         answer("A discrete random varible, since weights are often measured to the nearest pound."))
```

### 19.

```{r q19}
question("A young meteorologist is trying to estimate the expected number of tropical cyclones that occur in a given year. 
         He assumes that the number of observed tropical cyclones in a year follows a Poisson distribution with rate 
         $\\lambda$ that is consistent across years.  
         Because the meteorologist is inexperienced, he assigns a relatively uninformative $\\Gamma(k = .5,\\theta = 2)$ prior 
         distribution to $\\lambda$. During his first five years, he observes a total of 49 cyclones.  
         If he were to collect more data about tropical cyclones in future years, what should his prior be?",
         answer(sprintf("$\\Gamma(k = 49.5,\\theta = 2/21)$")),
         answer(sprintf("$\\Gamma(k = 49.5,\\theta = 2/11)$"),correct = TRUE),
         answer(sprintf("$\\Gamma(k = 49,\\theta = 7)$")),
         answer(sprintf("$\\Gamma(k = 49.5,\\theta = 7$")))
```

```{r 19a,exercise = TRUE}

```